app:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - /var/www/html/recipe/images:/data
    - /var/log/meteor:/var/log/meteor
    - ./run.config:/etc/service/meteor/run.config
  links:
    - mongodb
  restart: always
mongodb:
  image: tozd/meteor-mongodb:3.4
  volumes:
    - /var/recipe/mongo:/data/db
    - ./run.config:/etc/service/meteor/run.config
  restart: always
