app:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - /var/www/html/recipe/images:/data
  links:
    - mongo
  environment:
    - ROOT_URL=https://rezepte.ewald-moitzi.at
    - MONGO_URL=mongodb://mongo:27017/meteor
mongo:
  image: mongo:latest
  volumes:
    - /var/recipe/mongo:/data/db
