app:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - /var/www/html/recipe/images:/data
    - /var/log/meteor:/var/log/meteor
    - ./run.env:/etc/service/meteor/run.env
  links:
    - mongodb
  restart: always
mongodb:
  image: mongo:latest
  volumes:
    - /var/recipe/mongo:/data/db
  restart: always
